<html>
<head>
	<title>Kohana</title>
</head>
<body>
	<h1>
		Welcome to Kohana project
	</h1>

	<h2>
		That were been generated by kohana-scaffold. Check this out on <a href="http://github.com/loldesign/kohana-scaffold" target="_blank">our Github page</a>
	</h2>
</body>
</html>