<h1>Welcome to Kohana project</h1>

<p class="lead">That were been generated by kohana-scaffold.</p>
<p>
  Developed by <a href="http://loldesign.com.br" target="_blank" title="Loldesign">Loldesign</a> with the awesome Front-End Framework <a href="http://gumbyframework.com/" target="_blank" title="Gumby">Gumby</a> :)
</p>

<div class="medium primary btn">
	<a href="http://github.com/loldesign/kohana-scaffold" target="_blank">Github</a>
</div>
